// AjutsCat — mocked aid data, real Catalan aids
// Today (prototype reference date): 2026-04-21

window.AIDS = [
  {
    id: 'bo-lloguer-jove-2026',
    nombre_ca: 'Bo Lloguer Jove',
    nombre_es: 'Bono Alquiler Joven',
    subtitle_ca: 'Ajut mensual per a joves de 18 a 35 anys que viuen de lloguer',
    subtitle_es: 'Ayuda mensual para jóvenes de 18 a 35 años que viven de alquiler',
    categoria: 'vivienda',
    subcategoria: 'lloguer',
    cuantia_ca: '250 €/mes · 24 mesos',
    cuantia_es: '250 €/mes · 24 meses',
    cuantia_total_max: 6000,
    edad_min: 18,
    edad_max: 35,
    ingresos_max: 25200,
    ambito: 'catalunya',
    zonas: [],
    estado: 'cerrada',
    fecha_apertura: '2026-03-09',
    fecha_cierre: '2026-03-13',
    duracion_ventana_dias: 5,
    fuente: 'tramits.gencat.cat',
    organismo_ca: "Agència de l'Habitatge de Catalunya",
    organismo_es: "Agencia de la Vivienda de Cataluña",
    historico: [
      { ano: 2025, apertura: '2025-03-10', cierre: '2025-03-14', dias: 5 },
      { ano: 2024, apertura: '2024-04-02', cierre: '2024-04-12', dias: 11 },
      { ano: 2023, apertura: '2023-05-08', cierre: '2023-06-09', dias: 33 },
      { ano: 2026, apertura: '2026-03-09', cierre: '2026-03-13', dias: 5 },
    ],
    requisitos_ca: [
      'Tenir entre 18 i 35 anys (inclosos).',
      'Estar empadronat/da a Catalunya.',
      'Ingressos inferiors a 3× IRSC (≈ 25.200 €/any).',
      'Import del lloguer inferior a 900 € (Barcelona) o 600 € (resta).',
      'Ser titular del contracte de lloguer.',
    ],
    requisitos_es: [
      'Tener entre 18 y 35 años (incluidos).',
      'Estar empadronado/a en Catalunya.',
      'Ingresos inferiores a 3× IRSC (≈ 25.200 €/año).',
      'Importe del alquiler inferior a 900 € (Barcelona) o 600 € (resto).',
      'Ser titular del contrato de alquiler.',
    ],
    documentacion_ca: [
      'DNI / NIE vigent',
      'Contracte de lloguer signat',
      'Últims 3 rebuts de lloguer',
      'Certificat d\'empadronament',
      'Declaració de la renda (o certificat d\'imputacions)',
      'Certificat bancari de titularitat del compte',
    ],
    documentacion_es: [
      'DNI / NIE vigente',
      'Contrato de alquiler firmado',
      'Últimos 3 recibos de alquiler',
      'Certificado de empadronamiento',
      'Declaración de la renta (o certificado de imputaciones)',
      'Certificado bancario de titularidad de la cuenta',
    ],
    url_oficial: 'https://tramits.gencat.cat/',
    ultima_actualizacion: '2026-04-21',
  },
  {
    id: 'subvencio-lloguer-joves',
    nombre_ca: 'Subvenció lloguer · joves',
    nombre_es: 'Subvención alquiler · jóvenes',
    subtitle_ca: 'Franja d\'edat menors de 36 anys',
    subtitle_es: 'Franja de edad menores de 36 años',
    categoria: 'vivienda',
    subcategoria: 'lloguer',
    cuantia_ca: 'Fins al 40% del lloguer anual',
    cuantia_es: 'Hasta el 40% del alquiler anual',
    cuantia_total_max: 2400,
    edad_min: 18,
    edad_max: 35,
    ingresos_max: 25200,
    ambito: 'catalunya',
    zonas: [],
    estado: 'abierta',
    fecha_apertura: '2026-04-14',
    fecha_cierre: '2026-04-30',
    duracion_ventana_dias: 17,
    fuente: 'habitatge.gencat.cat',
    organismo_ca: "Agència de l'Habitatge de Catalunya",
    organismo_es: "Agencia de la Vivienda de Cataluña",
    historico: [
      { ano: 2025, apertura: '2025-04-10', cierre: '2025-05-02', dias: 23 },
      { ano: 2024, apertura: '2024-04-15', cierre: '2024-05-15', dias: 31 },
      { ano: 2023, apertura: '2023-03-01', cierre: '2023-04-15', dias: 46 },
      { ano: 2026, apertura: '2026-04-14', cierre: '2026-04-30', dias: 17 },
    ],
    requisitos_ca: [
      'Tenir menys de 36 anys.',
      'Ingressos entre 0,7 i 3,05 IRSC.',
      'Lloguer inferior als límits per zona.',
    ],
    requisitos_es: [
      'Tener menos de 36 años.',
      'Ingresos entre 0,7 y 3,05 IRSC.',
      'Alquiler inferior a los límites por zona.',
    ],
    documentacion_ca: [
      'DNI / NIE',
      'Contracte de lloguer',
      'Rebuts dels últims mesos',
      'Empadronament',
      'Declaració de renda',
    ],
    documentacion_es: [
      'DNI / NIE',
      'Contrato de alquiler',
      'Recibos de los últimos meses',
      'Empadronamiento',
      'Declaración de renta',
    ],
    url_oficial: 'https://habitatge.gencat.cat/',
    ultima_actualizacion: '2026-04-21',
  },
  {
    id: 'subvencio-lloguer-general',
    nombre_ca: 'Subvenció lloguer · general',
    nombre_es: 'Subvención alquiler · general',
    subtitle_ca: 'Per a persones de 36 a 64 anys',
    subtitle_es: 'Para personas de 36 a 64 años',
    categoria: 'vivienda',
    subcategoria: 'lloguer',
    cuantia_ca: 'Fins al 20% del lloguer anual',
    cuantia_es: 'Hasta el 20% del alquiler anual',
    cuantia_total_max: 2400,
    edad_min: 36,
    edad_max: 64,
    ingresos_max: 24300,
    ambito: 'catalunya',
    zonas: [],
    estado: 'proxima',
    fecha_apertura: '2026-05-05',
    fecha_cierre: '2026-06-15',
    duracion_ventana_dias: 41,
    fuente: 'habitatge.gencat.cat',
    organismo_ca: "Agència de l'Habitatge de Catalunya",
    organismo_es: "Agencia de la Vivienda de Cataluña",
    historico: [
      { ano: 2025, apertura: '2025-05-02', cierre: '2025-06-18', dias: 48 },
      { ano: 2024, apertura: '2024-05-08', cierre: '2024-06-30', dias: 54 },
    ],
    requisitos_ca: [
      'Edat entre 36 i 64 anys.',
      'Ingressos sota el llindar d\'IRSC.',
      'Contracte de lloguer vigent.',
    ],
    requisitos_es: [
      'Edad entre 36 y 64 años.',
      'Ingresos por debajo del umbral IRSC.',
      'Contrato de alquiler vigente.',
    ],
    documentacion_ca: ['DNI / NIE', 'Contracte de lloguer', 'Rebuts', 'Empadronament'],
    documentacion_es: ['DNI / NIE', 'Contrato de alquiler', 'Recibos', 'Empadronamiento'],
    url_oficial: 'https://habitatge.gencat.cat/',
    ultima_actualizacion: '2026-04-21',
  },
  {
    id: 'subvencio-lloguer-gent-gran',
    nombre_ca: 'Subvenció lloguer · gent gran',
    nombre_es: 'Subvención alquiler · mayores',
    subtitle_ca: 'Per a persones de 65 anys o més',
    subtitle_es: 'Para personas de 65 años o más',
    categoria: 'vivienda',
    subcategoria: 'lloguer',
    cuantia_ca: 'Fins al 60% del lloguer anual',
    cuantia_es: 'Hasta el 60% del alquiler anual',
    cuantia_total_max: 3600,
    edad_min: 65,
    edad_max: 120,
    ingresos_max: 20400,
    ambito: 'catalunya',
    zonas: [],
    estado: 'abierta',
    fecha_apertura: '2026-04-07',
    fecha_cierre: '2026-04-24',
    duracion_ventana_dias: 18,
    fuente: 'habitatge.gencat.cat',
    organismo_ca: "Agència de l'Habitatge de Catalunya",
    organismo_es: "Agencia de la Vivienda de Cataluña",
    historico: [
      { ano: 2025, apertura: '2025-04-08', cierre: '2025-05-05', dias: 28 },
      { ano: 2024, apertura: '2024-04-12', cierre: '2024-05-10', dias: 29 },
    ],
    requisitos_ca: [
      'Tenir 65 anys o més.',
      'Ingressos sota el llindar.',
      'Contracte de lloguer al propi nom.',
    ],
    requisitos_es: [
      'Tener 65 años o más.',
      'Ingresos por debajo del umbral.',
      'Contrato de alquiler a nombre propio.',
    ],
    documentacion_ca: ['DNI', 'Contracte de lloguer', 'Pensió / renda', 'Empadronament'],
    documentacion_es: ['DNI', 'Contrato de alquiler', 'Pensión / renta', 'Empadronamiento'],
    url_oficial: 'https://habitatge.gencat.cat/',
    ultima_actualizacion: '2026-04-21',
  },
  {
    id: 'prestacions-especial-urgencia',
    nombre_ca: "Prestacions d'especial urgència",
    nombre_es: 'Prestaciones de especial urgencia',
    subtitle_ca: 'Per a situacions de pèrdua d\'habitatge o deutes',
    subtitle_es: 'Para situaciones de pérdida de vivienda o deudas',
    categoria: 'vivienda',
    subcategoria: 'urgencia',
    cuantia_ca: 'Fins a 3.000 € en un pagament únic',
    cuantia_es: 'Hasta 3.000 € en un pago único',
    cuantia_total_max: 3000,
    edad_min: 18,
    edad_max: 120,
    ingresos_max: 22800,
    ambito: 'catalunya',
    zonas: [],
    estado: 'abierta',
    fecha_apertura: '2026-01-01',
    fecha_cierre: '2026-12-31',
    duracion_ventana_dias: 365,
    fuente: 'habitatge.gencat.cat',
    organismo_ca: "Agència de l'Habitatge de Catalunya",
    organismo_es: "Agencia de la Vivienda de Cataluña",
    historico: [
      { ano: 2025, apertura: '2025-01-01', cierre: '2025-12-31', dias: 365 },
      { ano: 2024, apertura: '2024-01-01', cierre: '2024-12-31', dias: 366 },
    ],
    requisitos_ca: [
      'Risc real d\'exclusió residencial.',
      'Informe dels serveis socials.',
      'Ingressos baixos.',
    ],
    requisitos_es: [
      'Riesgo real de exclusión residencial.',
      'Informe de servicios sociales.',
      'Ingresos bajos.',
    ],
    documentacion_ca: [
      'Informe de serveis socials',
      'DNI / NIE',
      'Contracte o sentència',
      'Justificant d\'ingressos',
    ],
    documentacion_es: [
      'Informe de servicios sociales',
      'DNI / NIE',
      'Contrato o sentencia',
      'Justificante de ingresos',
    ],
    url_oficial: 'https://habitatge.gencat.cat/',
    ultima_actualizacion: '2026-04-18',
    stale: true,
  },
  {
    id: 'consorci-habitatge-bcn-rehabilitacio',
    nombre_ca: 'Rehabilitació · Consorci BCN',
    nombre_es: 'Rehabilitación · Consorcio BCN',
    subtitle_ca: 'Per a obres de rehabilitació en edificis de Barcelona',
    subtitle_es: 'Para obras de rehabilitación en edificios de Barcelona',
    categoria: 'vivienda',
    subcategoria: 'rehabilitacio',
    cuantia_ca: 'Fins al 50% del cost de l\'obra',
    cuantia_es: 'Hasta el 50% del coste de la obra',
    cuantia_total_max: 20000,
    edad_min: 18,
    edad_max: 120,
    ingresos_max: null,
    ambito: 'barcelona',
    zonas: ['Barcelona ciutat'],
    estado: 'abierta',
    fecha_apertura: '2026-02-15',
    fecha_cierre: '2026-04-23',
    duracion_ventana_dias: 68,
    fuente: 'habitatge.barcelona',
    organismo_ca: "Consorci de l'Habitatge de Barcelona",
    organismo_es: "Consorcio de la Vivienda de Barcelona",
    historico: [
      { ano: 2025, apertura: '2025-02-10', cierre: '2025-04-30', dias: 80 },
      { ano: 2024, apertura: '2024-02-20', cierre: '2024-05-15', dias: 86 },
    ],
    requisitos_ca: [
      'Edifici situat a Barcelona ciutat.',
      'Acord de la comunitat de propietaris.',
      'Informe tècnic de l\'edifici.',
    ],
    requisitos_es: [
      'Edificio situado en Barcelona ciudad.',
      'Acuerdo de la comunidad de propietarios.',
      'Informe técnico del edificio.',
    ],
    documentacion_ca: [
      'Acta de la comunitat',
      'Informe tècnic (IITE)',
      'Projecte d\'obres',
      'Pressupost',
    ],
    documentacion_es: [
      'Acta de la comunidad',
      'Informe técnico (IITE)',
      'Proyecto de obras',
      'Presupuesto',
    ],
    url_oficial: 'https://habitatge.barcelona/',
    ultima_actualizacion: '2026-04-21',
  },
  {
    id: 'ajut-jove-compra',
    nombre_ca: 'Ajut Jove · compra habitatge',
    nombre_es: 'Ayuda Joven · compra vivienda',
    subtitle_ca: 'Per a la compra del primer habitatge habitual',
    subtitle_es: 'Para la compra de la primera vivienda habitual',
    categoria: 'vivienda',
    subcategoria: 'compra',
    cuantia_ca: 'Fins a 10.800 € (20% preu)',
    cuantia_es: 'Hasta 10.800 € (20% precio)',
    cuantia_total_max: 10800,
    edad_min: 18,
    edad_max: 35,
    ingresos_max: 37800,
    ambito: 'catalunya',
    zonas: ['municipis de menys de 10.000 habitants'],
    estado: 'cerrada',
    fecha_apertura: '2026-01-15',
    fecha_cierre: '2026-02-28',
    duracion_ventana_dias: 45,
    fuente: 'habitatge.gencat.cat',
    organismo_ca: "Agència de l'Habitatge de Catalunya",
    organismo_es: "Agencia de la Vivienda de Cataluña",
    historico: [
      { ano: 2025, apertura: '2025-01-20', cierre: '2025-03-05', dias: 44 },
      { ano: 2024, apertura: '2024-02-01', cierre: '2024-03-30', dias: 58 },
    ],
    requisitos_ca: [
      'Menors de 36 anys.',
      'Primer habitatge habitual.',
      'Municipi de menys de 10.000 habitants.',
      'Preu de compra inferior a 120.000 €.',
    ],
    requisitos_es: [
      'Menores de 36 años.',
      'Primera vivienda habitual.',
      'Municipio de menos de 10.000 habitantes.',
      'Precio de compra inferior a 120.000 €.',
    ],
    documentacion_ca: [
      'DNI / NIE',
      'Escriptura o contracte d\'arres',
      'Empadronament',
      'Declaració de renda',
    ],
    documentacion_es: [
      'DNI / NIE',
      'Escritura o contrato de arras',
      'Empadronamiento',
      'Declaración de renta',
    ],
    url_oficial: 'https://habitatge.gencat.cat/',
    ultima_actualizacion: '2026-04-21',
  },
  {
    id: 'mesures-antidesnonament',
    nombre_ca: "Mesures contra el desnonament",
    nombre_es: 'Medidas contra el desahucio',
    subtitle_ca: "Ajut per evitar la pèrdua de l'habitatge per impagament",
    subtitle_es: 'Ayuda para evitar la pérdida de la vivienda por impago',
    categoria: 'vivienda',
    subcategoria: 'urgencia',
    cuantia_ca: 'Fins a 6 mesos de lloguer pendent',
    cuantia_es: 'Hasta 6 meses de alquiler pendiente',
    cuantia_total_max: 5400,
    edad_min: 18,
    edad_max: 120,
    ingresos_max: 22800,
    ambito: 'catalunya',
    zonas: [],
    estado: 'abierta',
    fecha_apertura: '2026-04-18',
    fecha_cierre: '2026-04-23',
    duracion_ventana_dias: 6,
    fuente: 'habitatge.gencat.cat',
    organismo_ca: "Agència de l'Habitatge de Catalunya",
    organismo_es: "Agencia de la Vivienda de Cataluña",
    historico: [
      { ano: 2025, apertura: '2025-04-20', cierre: '2025-04-27', dias: 8 },
      { ano: 2024, apertura: '2024-04-15', cierre: '2024-04-25', dias: 11 },
      { ano: 2023, apertura: '2023-05-01', cierre: '2023-05-15', dias: 15 },
    ],
    requisitos_ca: [
      'Demanda judicial activa o notificació de desnonament.',
      'Ingressos inferiors a 2× IRSC.',
      'No tenir altres habitatges en propietat.',
    ],
    requisitos_es: [
      'Demanda judicial activa o notificación de desahucio.',
      'Ingresos inferiores a 2× IRSC.',
      'No tener otras viviendas en propiedad.',
    ],
    documentacion_ca: [
      'Notificació judicial',
      'Informe de serveis socials',
      'Justificant d\'ingressos',
      'Contracte de lloguer',
    ],
    documentacion_es: [
      'Notificación judicial',
      'Informe de servicios sociales',
      'Justificante de ingresos',
      'Contrato de alquiler',
    ],
    url_oficial: 'https://habitatge.gencat.cat/',
    ultima_actualizacion: '2026-04-21',
  },
];

window.I18N = {
  ca: {
    site_name: 'AjutsCat',
    tagline: 'Ajuts i subvencions de Catalunya, finalment entendibles.',
    intro: 'Un catàleg viu de les ajudes d\'habitatge obertes ara mateix. Actualitzat cada dia, abans que s\'acabi la finestra.',
    profile_prompt: 'Tinc',
    profile_age: 'anys',
    profile_live: 'i visc a',
    profile_any_age: 'qualsevol edat',
    profile_any_zone: 'qualsevol lloc',
    profile_apply: 'Filtra pel meu perfil',
    profile_clear: 'Esborra filtres',
    status_abierta: 'Oberta',
    status_cerrada: 'Tancada',
    status_proxima: 'Pròximament',
    status_desconegut: 'Info desactualitzada',
    card_amount: 'Quantia',
    card_age: 'Edat',
    card_deadline: 'Tanca el',
    card_opens: 'Obre el',
    card_closed_on: 'Va tancar el',
    card_days_left: 'dies',
    card_days_left_single: 'dia',
    card_urgent: 'Urgent',
    card_long_window: 'Tot l\'any',
    filter_all: 'Totes',
    filter_status: 'Estat',
    filter_type: 'Tipus',
    filter_zone: 'Zona',
    filter_type_lloguer: 'Lloguer',
    filter_type_compra: 'Compra',
    filter_type_rehabilitacio: 'Rehabilitació',
    filter_type_urgencia: 'Urgència',
    filter_zone_catalunya: 'Tota Catalunya',
    filter_zone_bcn: 'Barcelona ciutat',
    sort_by: 'Ordenar per',
    sort_urgency: 'Tanquen abans',
    sort_amount: 'Quantia més alta',
    sort_alpha: 'Alfabètic',
    results_count: 'ajudes',
    no_results: 'Cap ajuda coincideix amb els filtres.',
    clear_filters: 'Treu els filtres',
    card_cta: 'Veure detall',
    detail_requirements: 'Requisits',
    detail_docs: 'Documentació necessària',
    detail_how: 'Com demanar-la',
    detail_history: 'Convocatòries anteriors',
    detail_official: 'Anar al tràmit oficial →',
    detail_back: '← Tornar al llistat',
    detail_updated: 'Actualitzat',
    history_year: 'Any',
    history_open: 'Obertura',
    history_close: 'Tancament',
    history_days: 'Dies oberta',
    disclaimer_title: 'Info no oficial',
    disclaimer: 'AjutsCat és una capa humana sobre dades públiques. Verifica sempre a la font oficial abans de presentar la sol·licitud.',
    footer_about: 'Sobre el projecte',
    footer_source: 'Codi font',
    footer_contact: 'Contacte',
    hero_stat_open: 'ajudes obertes ara',
    hero_stat_soon: 'obriran aviat',
    hero_stat_closing: 'tanquen aquesta setmana',
    banner_urgent: 'Tanca avui o demà:',
    banner_urgent_cta: 'Veure',
  },
  es: {
    site_name: 'AjutsCat',
    tagline: 'Ayudas y subvenciones de Catalunya, por fin entendibles.',
    intro: 'Un catálogo vivo de las ayudas de vivienda abiertas ahora mismo. Actualizado cada día, antes de que se acabe la ventana.',
    profile_prompt: 'Tengo',
    profile_age: 'años',
    profile_live: 'y vivo en',
    profile_any_age: 'cualquier edad',
    profile_any_zone: 'cualquier lugar',
    profile_apply: 'Filtra por mi perfil',
    profile_clear: 'Quitar filtros',
    status_abierta: 'Abierta',
    status_cerrada: 'Cerrada',
    status_proxima: 'Próximamente',
    status_desconegut: 'Info desactualizada',
    card_amount: 'Cuantía',
    card_age: 'Edad',
    card_deadline: 'Cierra el',
    card_opens: 'Abre el',
    card_closed_on: 'Cerró el',
    card_days_left: 'días',
    card_days_left_single: 'día',
    card_urgent: 'Urgente',
    card_long_window: 'Todo el año',
    filter_all: 'Todas',
    filter_status: 'Estado',
    filter_type: 'Tipo',
    filter_zone: 'Zona',
    filter_type_lloguer: 'Alquiler',
    filter_type_compra: 'Compra',
    filter_type_rehabilitacio: 'Rehabilitación',
    filter_type_urgencia: 'Urgencia',
    filter_zone_catalunya: 'Toda Catalunya',
    filter_zone_bcn: 'Barcelona ciudad',
    sort_by: 'Ordenar por',
    sort_urgency: 'Cierran antes',
    sort_amount: 'Cuantía más alta',
    sort_alpha: 'Alfabético',
    results_count: 'ayudas',
    no_results: 'Ninguna ayuda coincide con los filtros.',
    clear_filters: 'Quitar filtros',
    card_cta: 'Ver detalle',
    detail_requirements: 'Requisitos',
    detail_docs: 'Documentación necesaria',
    detail_how: 'Cómo solicitarla',
    detail_history: 'Convocatorias anteriores',
    detail_official: 'Ir al trámite oficial →',
    detail_back: '← Volver al listado',
    detail_updated: 'Actualizado',
    history_year: 'Año',
    history_open: 'Apertura',
    history_close: 'Cierre',
    history_days: 'Días abierta',
    disclaimer_title: 'Info no oficial',
    disclaimer: 'AjutsCat es una capa humana sobre datos públicos. Verifica siempre en la fuente oficial antes de presentar la solicitud.',
    footer_about: 'Sobre el proyecto',
    footer_source: 'Código fuente',
    footer_contact: 'Contacto',
    hero_stat_open: 'ayudas abiertas ahora',
    hero_stat_soon: 'abren pronto',
    hero_stat_closing: 'cierran esta semana',
    banner_urgent: 'Cierra hoy o mañana:',
    banner_urgent_cta: 'Ver',
  }
};

// Prototype reference date, used instead of `new Date()` so the prototype is stable.
window.TODAY = new Date('2026-04-21T12:00:00');
